# Generated by Django 2.0 on 2018-10-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneRiddles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riddles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('hint', models.TextField()),
                ('points', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='doneriddles',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.MyUser'),
        ),
        migrations.AddField(
            model_name='doneriddles',
            name='riddles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.Riddles'),
        ),
    ]
