# Generated by Django 2.0 on 2018-10-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0006_auto_20181004_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneriddles',
            name='curiosity',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='riddles.Curiosity'),
            preserve_default=False,
        ),
    ]
