# Generated by Django 2.0 on 2018-10-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0007_doneriddles_curiosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneCuriosity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curiosity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.Curiosity')),
            ],
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['points']},
        ),
        migrations.RemoveField(
            model_name='doneriddles',
            name='curiosity',
        ),
        migrations.AddField(
            model_name='donecuriosity',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddles.MyUser'),
        ),
    ]
